name: Automated Release Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # Job: Build binaries for multiple platforms
  build:
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
            ext: ''
          - os: macos-latest
            platform: macos
            arch: x64
            ext: ''
          - os: windows-latest
            platform: windows
            arch: x64
            ext: '.exe'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Create binary
        run: pkg dist/index.js --targets node18-${{ matrix.platform }}-${{ matrix.arch }} --output gh-manager-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.ext }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gh-manager-${{ matrix.platform }}-${{ matrix.arch }}
          path: gh-manager-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.ext }}
          retention-days: 90

  # Job: Create automated release using semantic-release
  create-release:
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./binaries

      - name: Display downloaded artifacts
        run: |
          ls -la ./binaries/
          find ./binaries -type f -exec ls -la {} \;

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create .npmrc for GitHub Packages
          echo "@wiiiimm:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          
          # Temporarily update package.json for scoped publishing
          sed -i 's/"name": "gh-manager-cli"/"name": "@wiiiimm\/gh-manager-cli"/' package.json
          
          # Publish to GitHub Packages
          npm publish --registry=https://npm.pkg.github.com
          
          # Restore original package.json
          git checkout package.json